config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root 'static_pages#index'
  resources :places
  resources :stories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/story.rb
class Story < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index 
    @places = Place.all
  end


  def new 
    @place = Place.new 
  end 

  def create 
    Place.create(place_params)
    redirect_to root_path
  end 

  private 

  def place_params 
    params.require(:place).permit(:title, :description, :address)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index 
    @places = Place.all
    @stories = Story.all
  end

  def new 
    @place = Place.new
    @story = Story.new
  end

 
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index 
    @stories = Story.all
  end


  def new 
    @story = Story.new 
  end 

  def create 
    Story.create(story_params)
    redirect_to root_path
  end 

  def show 
    @story = Story.find(params[:id])
  end

  private 

  def story_params 
    params.require(:story).permit(:title, :description, :location)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Traveler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to 'Traveler', root_path, class:"navbar-brand" %>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-md-0">
            <li class="nav-item active">
              <%= link_to 'Home', root_path, class:"nav-link" %>

              <%= link_to 'Add a Story', new_story_path, class:"nav-link"%> 
            </li>
            
          </ul>
          
        </div>
       </nav>

    <%= yield %>


    <div class= "footer">
      <div class="container">
        <div class= "row"> 
          <div class="col -12 col-sm-6">
             <h4> <%= link_to 'Add A Story', new_story_path %> </h4>
          </div>
          <div class ="col-12 col-sm-6 footer-blurb">
            Developed Pete Spizzirri </a> 
            <br/>
          </div>
        </div>  
        <p class= "text-muted">  </p>
      </div>
    </div>
  </body>
</html>

app/views/places/new.html.erb
<div class= "booyah-box col-12">
  <br />
  <h1> Add Your Place </h1>
  <div class= "place_form" >
    <%= simple_form_for @place do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :address %>
      <%= f.submit 'Create', class:  'btn primary btn' %>

    <% end %> 
  </div>

</div> 

app/views/static_pages/index.html.erb
<br />





<body>
  <div class="title">
    <h1> Travel Journal  </h1>
  </div>

<div class= "booyah-box col-12">
  <% @places.each do |place| %>
    <div>
      <h2><%= place.title %></h2><br />
      <i><%= place.address %></i><br />
      <p><%= place.description %></p><br />
    </div>

    <hr />
  <% end %>
</div>


<div class = "booyah-box col-12 ">
  <% @stories.each do |story| %>
    <div>
      <h2><%= link_to story.title, story_path(story) %> </h2><br/>
    </div>
    <hr />
  <% end %> 


</div>

</body>

app/views/stories/new.html.erb
<div class= "booyah-box col-12">
  <br />
  <h1> Add Your Story </h1>
  <div class= "story_form" >
    <%= simple_form_for @story do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :location %>
      <%= f.input :event %>
      <%= f.submit 'Create', class:  'btn primary btn' %>

    <% end %> 
  </div>

</div> 

app/views/stories/show.html.erb
<div class = "booyah-box col-12 text-center">
  
    <div>
      <h2><%= @story.title %> </h2><br/>
      <i> <%= @story.description %></i><br />
      <p> <%= @story.location %></p> <br />
      <i> <%= @story.event %></i> <br />
    </div>
    <hr />



</div>